# Generated by Django 4.2.3 on 2023-08-03 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='subject',
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100, verbose_name="the person's name"),
        ),
        migrations.AlterField(
            model_name='test',
            name='grade',
            field=models.IntegerField(),
        ),
    ]
